---
name: 'Platforms'

on:
  push:
    branches:
      - plat-test
  pull_request:
    branches:
      - plat-test

  workflow_dispatch:

jobs:
  build_1:
    uses: Krishna-13-cyber/clad/.github/workflows/called.yml@plat-test
    with:
      username: x86

  build_2:
    uses: Krishna-13-cyber/clad/.github/workflows/called.yml@plat-test
    with:
      username: armv7