---
name: 'build images'

on:
  push:
    branches:
      - plat-test

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: krishna132002
          password: krishna_13

      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          tags: krishna132002/clad-test:latest
          platforms: linux/amd64,linux/ppc64le
          push: true