---
name: 'build images'

on:
  push:
    branches:
      - plat-test

jobs:
    build_simppru_job:
        runs-on: ubuntu-latest
        name: This will test simppru on amd64 machine
        
        steps: 
            - name: Checkout branch
              uses: actions/checkout@v3
            - name: "Setup latest Alpine Linux"
              uses: jirutka/setup-alpine@v1
              with:
                arch: x86
                branch: edge
                packages: >
                  llvm-dev
                  cmake
                  llvm
                  clang
                  make
                  git
            - name: "Setup"
              run: |
                clang --version
                make --version
              shell: alpine.sh {0}

            - name: "Compile library"
              run: |
                git clone https://github.com/vgvassilev/clad.git
                cd clad
                mkdir build && cd build
                cmake -DLLVM_DIR=/usr/lib/llvm-11/build/ -DCMAKE_BUILD_TYPE=DEBUG -DLLVM_EXTERNAL_LIT="$(which lit)" ../
              shell: alpine.sh {0}

            - name: "Check"
              run: |
                make -j 8 check-clad
              shell: alpine.sh {0}